# Generated by Django 4.2.1 on 2023-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiment', models.CharField(choices=[], max_length=20)),
                ('unit', models.CharField(choices=[], max_length=5)),
                ('in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery', models.CharField(choices=[], max_length=20)),
                ('unit', models.CharField(choices=[], max_length=5)),
                ('in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.CharField(choices=[], max_length=20)),
                ('unit', models.CharField(choices=[], max_length=5)),
                ('in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[], max_length=5)),
                ('in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Spice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spice', models.CharField(choices=[], max_length=20)),
                ('unit', models.CharField(choices=[], max_length=5)),
                ('in_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
